import mongoose from "mongoose";
import "dotenv/config";
import Hotel from "./models/hotel";
import User from "./models/user";


let hotelIndex = 0;

const allHotelImages = [
  // The Grand Taj Palace - Mumbai (luxury hotel exterior + room + lobby)
  ["https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80", "https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800&q=80", "https://images.unsplash.com/photo-1584132967334-10e028bd69f7?w=800&q=80"],
  // Ocean Pearl Resort - Goa (beach resort + pool + villa)
  ["https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&q=80", "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=800&q=80", "https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?w=800&q=80"],
  // Himalayan Serenity Retreat - Manali (mountain hotel + cabin + snow view)
  ["https://images.unsplash.com/photo-1585468274952-66591eb14165?w=800&q=80", "https://images.unsplash.com/photo-1568084680786-a84f91d1153c?w=800&q=80", "https://images.unsplash.com/photo-1549638441-b787d2e11f14?w=800&q=80"],
  // Royal Heritage Haveli - Jaipur (heritage palace + courtyard + suite)
  ["https://images.unsplash.com/photo-1590490359683-658d3d23f972?w=800&q=80", "https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=800&q=80", "https://images.unsplash.com/photo-1582719508461-905c673771fd?w=800&q=80"],
  // Alleppey Backwater Bliss - Kerala (houseboat + backwaters + sunset)
  ["https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?w=800&q=80", "https://images.unsplash.com/photo-1606402179428-a57976d71fa4?w=800&q=80", "https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800&q=80"],
  // The Garden City Inn - Bangalore (modern hotel + room + rooftop)
  ["https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800&q=80", "https://images.unsplash.com/photo-1560200353-ce0a76b1d438?w=800&q=80", "https://images.unsplash.com/photo-1584132967334-10e028bd69f7?w=800&q=80"],
  // Darjeeling Cloud Cottage - Darjeeling (mountain cottage + tea garden + view)
  ["https://images.unsplash.com/photo-1585468274952-66591eb14165?w=800&q=80", "https://images.unsplash.com/photo-1568084680786-a84f91d1153c?w=800&q=80", "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=800&q=80"],
  // Marina Bay Suites - Chennai (luxury suite + ocean view + city)
  ["https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80", "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=800&q=80", "https://images.unsplash.com/photo-1582719508461-905c673771fd?w=800&q=80"],
  // Saffron Palm Resort - Kerala (luxury resort + spa + pool)
  ["https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800&q=80", "https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?w=800&q=80", "https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=800&q=80"],
  // Shimla Pine Retreat - Shimla (pine forest resort + room + mountain)
  ["https://images.unsplash.com/photo-1585468274952-66591eb14165?w=800&q=80", "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=800&q=80", "https://images.unsplash.com/photo-1568084680786-a84f91d1153c?w=800&q=80"],
  // Udaipur Lotus Palace - Udaipur (lake palace + courtyard + royal suite)
  ["https://images.unsplash.com/photo-1540541338287-41700207dee6?w=800&q=80", "https://images.unsplash.com/photo-1590490359683-658d3d23f972?w=800&q=80", "https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=800&q=80"],
  // Rann Utsav Resort - Kutch (desert resort + tent + sunset)
  ["https://images.unsplash.com/photo-1606402179428-a57976d71fa4?w=800&q=80", "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&q=80", "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800&q=80"],
  // Ganges View Bungalow - Varanasi (ganges view + heritage + suite)
  ["https://images.unsplash.com/photo-1560200353-ce0a76b1d438?w=800&q=80", "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=800&q=80", "https://images.unsplash.com/photo-1582719508461-905c673771fd?w=800&q=80"],
  // Amber Valley Resort - Jaipur (desert resort + pool + palace)
  ["https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80", "https://images.unsplash.com/photo-1590490359683-658d3d23f972?w=800&q=80", "https://images.unsplash.com/photo-1584132967334-10e028bd69f7?w=800&q=80"],
  // Assam Tea Estate Bungalow - Assam (tea garden + colonial + bungalow)
  ["https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?w=800&q=80", "https://images.unsplash.com/photo-1568084680786-a84f91d1153c?w=800&q=80", "https://images.unsplash.com/photo-1585468274952-66591eb14165?w=800&q=80"],
  // Coral Reef Resort - Havelock (beach resort + coral + island)
  ["https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&q=80", "https://images.unsplash.com/photo-1606402179428-a57976d71fa4?w=800&q=80", "https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800&q=80"],
  // Stepwell View Hotel - Jodhpur (blue city hotel + stepwell + suite)
  ["https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=800&q=80", "https://images.unsplash.com/photo-1585468274952-66591eb14165?w=800&q=80", "https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=800&q=80"],
  // Coorg Spice Garden Stay - Coorg (plantation + cottage + forest)
  ["https://images.unsplash.com/photo-1568084680786-a84f91d1153c?w=800&q=80", "https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?w=800&q=80", "https://images.unsplash.com/photo-1606402179428-a57976d71fa4?w=800&q=80"],
  // Gateway to India Hotel - Mumbai (heritage + sea view + luxury)
  ["https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80", "https://images.unsplash.com/photo-1582719508461-905c673771fd?w=800&q=80", "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=800&q=80"],
  // Naini Lake Resort - Nainital (lake resort + hills + cottage)
  ["https://images.unsplash.com/photo-1584132967334-10e028bd69f7?w=800&q=80", "https://images.unsplash.com/photo-1590490359683-658d3d23f972?w=800&q=80", "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800&q=80"],
];

const hotels = [
  {
    name: "The Grand Taj Palace",
    city: "Mumbai",
    country: "India",
    description: "Experience luxury at its finest in the heart of Mumbai. The Grand Taj Palace offers breathtaking views of the Arabian Sea, world-class dining, and impeccable service that will make your stay unforgettable.",
    type: ["Hotel", "Resort"],
    adultCount: 4,
    childCount: 2,
    facilities: ["Free WiFi", "Swimming Pool", "Spa", "Restaurant", "Fitness Center", "Airport Shuttle", "Bar/Lounge", "Free Parking"],
    pricePerNight: 8500,
    starRating: 5,
    imageUrls: allHotelImages[hotelIndex++],
    contact: { phone: "+91-22-6665-3366", email: "reservations@tajpalace.com", website: "https://www.tajhotels.com" },
    policies: { checkInTime: "2:00 PM", checkOutTime: "12:00 PM", cancellationPolicy: "Free cancellation up to 48 hours before check-in", petPolicy: "Pets not allowed", smokingPolicy: "Non-smoking property" },
    amenities: { wifi: true, pool: true, spa: true, restaurant: true, gym: true, bar: true, airportShuttle: true, businessCenter: true, parking: true },
    isFeatured: true,
    smartScore: 95,
    ecoScore: 78,
    ecoBadges: ["Solar Powered", "Water Conservation"],
    moodTags: ["luxury", "romantic", "business"],
    nearbyExperiences: [{ name: "Gateway of India", type: "Monument", distance: "2 km", rating: 4.7 }, { name: "Marine Drive", type: "Beachfront", distance: "1 km", rating: 4.5 }],
    location: { latitude: 18.922, longitude: 72.8347, address: { street: "Apollo Bunder", city: "Mumbai", state: "Maharashtra", country: "India", zipCode: "400001" } },
  },
  {
    name: "Sunrise Beach Resort",
    city: "Goa",
    country: "India",
    description: "Wake up to the sound of waves at Sunrise Beach Resort. Nestled along the pristine shores of Calangute Beach, this tropical paradise offers direct beach access, infinity pools, and authentic Goan cuisine.",
    type: ["Resort"],
    adultCount: 3,
    childCount: 2,
    facilities: ["Free WiFi", "Swimming Pool", "Spa", "Restaurant", "Free Parking", "Bar/Lounge"],
    pricePerNight: 5200,
    starRating: 4,
    imageUrls: allHotelImages[hotelIndex++],
    contact: { phone: "+91-832-2277-330", email: "info@sunrisebeachgoa.com", website: "" },
    policies: { checkInTime: "1:00 PM", checkOutTime: "11:00 AM", cancellationPolicy: "Free cancellation up to 24 hours", petPolicy: "Small pets allowed with fee", smokingPolicy: "Designated smoking areas" },
    amenities: { wifi: true, pool: true, spa: true, restaurant: true, gym: false, bar: true, airportShuttle: false, businessCenter: false, parking: true },
    isFeatured: true,
    smartScore: 88,
    ecoScore: 82,
    ecoBadges: ["Beach Cleanup Program", "Local Sourcing"],
    moodTags: ["beach", "relaxation", "party"],
    nearbyExperiences: [{ name: "Calangute Beach", type: "Beach", distance: "0 km", rating: 4.3 }, { name: "Fort Aguada", type: "Historical", distance: "5 km", rating: 4.4 }],
    location: { latitude: 15.5439, longitude: 73.7553, address: { street: "Calangute Beach Road", city: "Goa", state: "Goa", country: "India", zipCode: "403516" } },
  },
  {
    name: "Himalayan Heights Lodge",
    city: "Manali",
    country: "India",
    description: "Perched in the lap of the Himalayas, this charming wooden lodge offers panoramic mountain views, cozy fireplaces, and easy access to trekking trails and ancient temples.",
    type: ["Cottage", "B&B"],
    adultCount: 4,
    childCount: 2,
    facilities: ["Free WiFi", "Free Parking", "Restaurant", "Fitness Center"],
    pricePerNight: 3800,
    starRating: 3,
    imageUrls: allHotelImages[hotelIndex++],
    contact: { phone: "+91-1902-253-500", email: "stay@himalayanheights.com", website: "" },
    policies: { checkInTime: "12:00 PM", checkOutTime: "11:00 AM", cancellationPolicy: "Free cancellation up to 72 hours", petPolicy: "Pets welcome", smokingPolicy: "Non-smoking rooms available" },
    amenities: { wifi: true, pool: false, spa: false, restaurant: true, gym: false, bar: false, airportShuttle: false, businessCenter: false, parking: true },
    smartScore: 82,
    ecoScore: 90,
    ecoBadges: ["Zero Waste", "Solar Powered", "Organic Garden"],
    moodTags: ["adventure", "nature", "peaceful"],
    nearbyExperiences: [{ name: "Rohtang Pass", type: "Mountain", distance: "45 km", rating: 4.8 }, { name: "Hidimba Temple", type: "Temple", distance: "3 km", rating: 4.2 }],
    location: { latitude: 32.2432, longitude: 77.1892, address: { street: "Old Manali Road", city: "Manali", state: "Himachal Pradesh", country: "India", zipCode: "175131" } },
  },
  {
    name: "The Royal Orchid",
    city: "Jaipur",
    country: "India",
    description: "Step into the world of Rajput grandeur. This heritage-inspired hotel features ornate architecture, royal suites, and proximity to the Pink City's most iconic landmarks.",
    type: ["Hotel"],
    adultCount: 3,
    childCount: 2,
    facilities: ["Free WiFi", "Swimming Pool", "Spa", "Restaurant", "Airport Shuttle", "Business Center", "Free Parking"],
    pricePerNight: 6200,
    starRating: 5,
    imageUrls: allHotelImages[hotelIndex++],
    contact: { phone: "+91-141-256-8000", email: "bookings@royalorchidjaipur.com", website: "https://www.royalorchid.com" },
    policies: { checkInTime: "2:00 PM", checkOutTime: "12:00 PM", cancellationPolicy: "Free cancellation up to 48 hours", petPolicy: "Pets not allowed", smokingPolicy: "Designated areas only" },
    amenities: { wifi: true, pool: true, spa: true, restaurant: true, gym: true, bar: true, airportShuttle: true, businessCenter: true, parking: true },
    smartScore: 91,
    ecoScore: 65,
    ecoBadges: ["Water Recycling"],
    moodTags: ["luxury", "cultural", "heritage"],
    nearbyExperiences: [{ name: "Hawa Mahal", type: "Palace", distance: "2 km", rating: 4.6 }, { name: "Amer Fort", type: "Fortress", distance: "11 km", rating: 4.7 }],
    location: { latitude: 26.9124, longitude: 75.7873, address: { street: "Station Road", city: "Jaipur", state: "Rajasthan", country: "India", zipCode: "302006" } },
  },
  {
    name: "Backwater Haven Houseboat",
    city: "Alleppey",
    country: "India",
    description: "Drift through Kerala's serene backwaters in a traditional houseboat. Enjoy home-cooked Keralan meals, stunning sunsets, and the gentle rhythm of village life along the waterways.",
    type: ["Villa", "B&B"],
    adultCount: 4,
    childCount: 2,
    facilities: ["Free WiFi", "Restaurant", "Free Parking"],
    pricePerNight: 7500,
    starRating: 4,
    imageUrls: allHotelImages[hotelIndex++],
    contact: { phone: "+91-477-226-0001", email: "info@backwaterhaven.in", website: "" },
    policies: { checkInTime: "12:00 PM", checkOutTime: "9:00 AM", cancellationPolicy: "50% refund if cancelled within 48 hours", petPolicy: "No pets", smokingPolicy: "Non-smoking" },
    amenities: { wifi: true, pool: false, spa: false, restaurant: true, gym: false, bar: false, airportShuttle: false, businessCenter: false, parking: true },
    isFeatured: true,
    smartScore: 86,
    ecoScore: 92,
    ecoBadges: ["Eco-Friendly Materials", "Local Community Support", "Zero Plastic"],
    moodTags: ["peaceful", "nature", "romantic"],
    nearbyExperiences: [{ name: "Kerala Backwaters", type: "Nature", distance: "0 km", rating: 4.9 }, { name: "Alleppey Beach", type: "Beach", distance: "8 km", rating: 4.1 }],
    location: { latitude: 9.4981, longitude: 76.3388, address: { street: "Punnamada Lake", city: "Alleppey", state: "Kerala", country: "India", zipCode: "688013" } },
  },
  {
    name: "Urban Nest Suites",
    city: "Bangalore",
    country: "India",
    description: "A modern boutique hotel in Bangalore's tech hub. Perfect for business travelers and city explorers with smart rooms, rooftop bar, and excellent connectivity to IT parks.",
    type: ["Hotel", "Apartment"],
    adultCount: 2,
    childCount: 1,
    facilities: ["Free WiFi", "Fitness Center", "Restaurant", "Business Center", "Airport Shuttle", "Free Parking"],
    pricePerNight: 4500,
    starRating: 4,
    imageUrls: allHotelImages[hotelIndex++],
    contact: { phone: "+91-80-4111-5555", email: "reservations@urbannest.in", website: "" },
    policies: { checkInTime: "2:00 PM", checkOutTime: "12:00 PM", cancellationPolicy: "Free cancellation up to 24 hours", petPolicy: "Pets not allowed", smokingPolicy: "Non-smoking property" },
    amenities: { wifi: true, pool: false, spa: false, restaurant: true, gym: true, bar: true, airportShuttle: true, businessCenter: true, parking: true },
    smartScore: 85,
    ecoScore: 72,
    ecoBadges: ["Energy Efficient"],
    moodTags: ["business", "modern", "city"],
    nearbyExperiences: [{ name: "Lalbagh Botanical Garden", type: "Garden", distance: "4 km", rating: 4.5 }, { name: "MG Road", type: "Shopping", distance: "2 km", rating: 4.3 }],
    location: { latitude: 12.9716, longitude: 77.5946, address: { street: "MG Road", city: "Bangalore", state: "Karnataka", country: "India", zipCode: "560001" } },
  },
  {
    name: "The Darjeeling Cloud Nine",
    city: "Darjeeling",
    country: "India",
    description: "Watch the sunrise over Kanchenjunga from your room. This colonial-era hotel combines vintage charm with modern amenities, offering warm hospitality in the Queen of Hills.",
    type: ["Hotel", "B&B"],
    adultCount: 3,
    childCount: 1,
    facilities: ["Free WiFi", "Restaurant", "Free Parking", "Spa"],
    pricePerNight: 4200,
    starRating: 4,
    imageUrls: allHotelImages[hotelIndex++],
    contact: { phone: "+91-354-225-4780", email: "stay@cloudninehotel.in", website: "" },
    policies: { checkInTime: "1:00 PM", checkOutTime: "11:00 AM", cancellationPolicy: "Free cancellation up to 48 hours", petPolicy: "No pets", smokingPolicy: "Designated areas" },
    amenities: { wifi: true, pool: false, spa: true, restaurant: true, gym: false, bar: false, airportShuttle: false, businessCenter: false, parking: true },
    smartScore: 80,
    ecoScore: 85,
    ecoBadges: ["Organic Tea Garden", "Local Sourcing"],
    moodTags: ["peaceful", "nature", "cultural"],
    nearbyExperiences: [{ name: "Tiger Hill", type: "Viewpoint", distance: "7 km", rating: 4.7 }, { name: "Darjeeling Himalayan Railway", type: "Heritage", distance: "1 km", rating: 4.6 }],
    location: { latitude: 27.041, longitude: 88.2663, address: { street: "Observatory Hill Road", city: "Darjeeling", state: "West Bengal", country: "India", zipCode: "734101" } },
  },
  {
    name: "Marina Bay Hotel",
    city: "Chennai",
    country: "India",
    description: "Located along Marina Beach, this hotel offers stunning ocean views, authentic South Indian cuisine, and easy access to historic temples and cultural attractions.",
    type: ["Hotel"],
    adultCount: 3,
    childCount: 2,
    facilities: ["Free WiFi", "Swimming Pool", "Restaurant", "Fitness Center", "Business Center", "Free Parking", "Bar/Lounge"],
    pricePerNight: 5800,
    starRating: 4,
    imageUrls: allHotelImages[hotelIndex++],
    contact: { phone: "+91-44-2852-4000", email: "info@marinabaychennai.com", website: "" },
    policies: { checkInTime: "2:00 PM", checkOutTime: "12:00 PM", cancellationPolicy: "Free cancellation up to 24 hours", petPolicy: "No pets", smokingPolicy: "Non-smoking rooms" },
    amenities: { wifi: true, pool: true, spa: false, restaurant: true, gym: true, bar: true, airportShuttle: true, businessCenter: true, parking: true },
    smartScore: 83,
    ecoScore: 68,
    ecoBadges: ["Rainwater Harvesting"],
    moodTags: ["city", "cultural", "food"],
    nearbyExperiences: [{ name: "Marina Beach", type: "Beach", distance: "0 km", rating: 4.4 }, { name: "Kapaleeshwarar Temple", type: "Temple", distance: "5 km", rating: 4.5 }],
    location: { latitude: 13.0827, longitude: 80.2707, address: { street: "Marina Beach Road", city: "Chennai", state: "Tamil Nadu", country: "India", zipCode: "600001" } },
  },
  {
    name: "Saffron Sands Villa",
    city: "Udaipur",
    country: "India",
    description: "A lakeside villa with private terraces overlooking Lake Pichola. Enjoy traditional Rajasthani hospitality, boat rides to the Lake Palace, and authentic local cuisine.",
    type: ["Villa"],
    adultCount: 4,
    childCount: 2,
    facilities: ["Free WiFi", "Swimming Pool", "Spa", "Restaurant", "Free Parking"],
    pricePerNight: 9200,
    starRating: 5,
    imageUrls: allHotelImages[hotelIndex++],
    contact: { phone: "+91-294-242-8800", email: "reservations@saffronsands.in", website: "" },
    policies: { checkInTime: "2:00 PM", checkOutTime: "12:00 PM", cancellationPolicy: "Free cancellation up to 72 hours", petPolicy: "No pets", smokingPolicy: "Non-smoking" },
    amenities: { wifi: true, pool: true, spa: true, restaurant: true, gym: false, bar: true, airportShuttle: false, businessCenter: false, parking: true },
    isFeatured: true,
    smartScore: 94,
    ecoScore: 80,
    ecoBadges: ["Solar Powered", "Heritage Conservation"],
    moodTags: ["luxury", "romantic", "heritage"],
    nearbyExperiences: [{ name: "City Palace", type: "Palace", distance: "1 km", rating: 4.6 }, { name: "Jagdish Temple", type: "Temple", distance: "1.5 km", rating: 4.4 }],
    location: { latitude: 24.5854, longitude: 73.7125, address: { street: "Lake Pichola", city: "Udaipur", state: "Rajasthan", country: "India", zipCode: "313001" } },
  },
  {
    name: "The Pine Retreat",
    city: "Shimla",
    country: "India",
    description: "Surrounded by dense deodar and pine forests, this cozy retreat offers breathtaking valley views, nature walks, and a warm fireplace for chilly mountain evenings.",
    type: ["Cottage"],
    adultCount: 4,
    childCount: 2,
    facilities: ["Free WiFi", "Free Parking", "Restaurant"],
    pricePerNight: 3200,
    starRating: 3,
    imageUrls: allHotelImages[hotelIndex++],
    contact: { phone: "+91-177-262-3400", email: "info@pineretreat.in", website: "" },
    policies: { checkInTime: "12:00 PM", checkOutTime: "11:00 AM", cancellationPolicy: "Free cancellation up to 48 hours", petPolicy: "Pets allowed", smokingPolicy: "Designated areas" },
    amenities: { wifi: true, pool: false, spa: false, restaurant: true, gym: false, bar: false, airportShuttle: false, businessCenter: false, parking: true },
    smartScore: 76,
    ecoScore: 88,
    ecoBadges: ["Forest Conservation", "Zero Plastic"],
    moodTags: ["nature", "peaceful", "adventure"],
    nearbyExperiences: [{ name: "The Mall Road", type: "Shopping", distance: "2 km", rating: 4.3 }, { name: "Jakhu Temple", type: "Temple", distance: "3 km", rating: 4.2 }],
    location: { latitude: 31.1048, longitude: 77.1734, address: { street: "The Mall", city: "Shimla", state: "Himachal Pradesh", country: "India", zipCode: "171001" } },
  },
  {
    name: "Lotus Palace Resort",
    city: "Kochi",
    country: "India",
    description: "A luxurious waterfront resort in Fort Kochi with colonial architecture, Ayurvedic spa treatments, and spectacular views of the Chinese fishing nets at sunset.",
    type: ["Resort", "Hotel"],
    adultCount: 3,
    childCount: 2,
    facilities: ["Free WiFi", "Swimming Pool", "Spa", "Restaurant", "Fitness Center", "Airport Shuttle", "Bar/Lounge", "Free Parking"],
    pricePerNight: 7800,
    starRating: 5,
    imageUrls: allHotelImages[hotelIndex++],
    contact: { phone: "+91-484-221-7000", email: "stay@lotuspalacekochi.com", website: "" },
    policies: { checkInTime: "2:00 PM", checkOutTime: "12:00 PM", cancellationPolicy: "Free cancellation up to 48 hours", petPolicy: "No pets", smokingPolicy: "Non-smoking property" },
    amenities: { wifi: true, pool: true, spa: true, restaurant: true, gym: true, bar: true, airportShuttle: true, businessCenter: true, parking: true },
    smartScore: 92,
    ecoScore: 84,
    ecoBadges: ["Ayurvedic Wellness", "Local Sourcing", "Water Conservation"],
    moodTags: ["luxury", "wellness", "cultural"],
    nearbyExperiences: [{ name: "Chinese Fishing Nets", type: "Landmark", distance: "0.5 km", rating: 4.5 }, { name: "Mattancherry Palace", type: "Palace", distance: "2 km", rating: 4.3 }],
    location: { latitude: 9.9312, longitude: 76.2673, address: { street: "Princess Street, Fort Kochi", city: "Kochi", state: "Kerala", country: "India", zipCode: "682001" } },
  },
  {
    name: "The Rann Tent City",
    city: "Bhuj",
    country: "India",
    description: "Experience the magical white desert of the Rann of Kutch in luxury Swiss tents. Enjoy folk dance performances, stargazing, and authentic Kutchi cuisine under the stars.",
    type: ["Resort"],
    adultCount: 2,
    childCount: 2,
    facilities: ["Free WiFi", "Restaurant", "Free Parking", "Spa"],
    pricePerNight: 6500,
    starRating: 4,
    imageUrls: allHotelImages[hotelIndex++],
    contact: { phone: "+91-2832-220-001", email: "info@ranntentcity.in", website: "" },
    policies: { checkInTime: "3:00 PM", checkOutTime: "10:00 AM", cancellationPolicy: "50% refund within 7 days", petPolicy: "No pets", smokingPolicy: "Designated areas" },
    amenities: { wifi: true, pool: false, spa: true, restaurant: true, gym: false, bar: false, airportShuttle: false, businessCenter: false, parking: true },
    isFeatured: true,
    smartScore: 87,
    ecoScore: 86,
    ecoBadges: ["Solar Powered", "Desert Conservation", "Local Artisan Support"],
    moodTags: ["adventure", "cultural", "unique"],
    nearbyExperiences: [{ name: "Rann of Kutch", type: "Desert", distance: "0 km", rating: 4.9 }, { name: "Kala Dungar", type: "Viewpoint", distance: "30 km", rating: 4.5 }],
    location: { latitude: 23.242, longitude: 69.6669, address: { street: "White Desert Road", city: "Bhuj", state: "Gujarat", country: "India", zipCode: "370001" } },
  },
  {
    name: "The Ganges View Inn",
    city: "Rishikesh",
    country: "India",
    description: "Wake up to the holy Ganges flowing right outside your window. This riverside inn is perfect for yoga enthusiasts, adventure seekers, and spiritual explorers.",
    type: ["B&B", "Hostel"],
    adultCount: 4,
    childCount: 1,
    facilities: ["Free WiFi", "Restaurant", "Free Parking", "Fitness Center"],
    pricePerNight: 2500,
    starRating: 3,
    imageUrls: allHotelImages[hotelIndex++],
    contact: { phone: "+91-135-243-0001", email: "stay@gangesview.in", website: "" },
    policies: { checkInTime: "12:00 PM", checkOutTime: "11:00 AM", cancellationPolicy: "Free cancellation up to 24 hours", petPolicy: "No pets", smokingPolicy: "Non-smoking" },
    amenities: { wifi: true, pool: false, spa: false, restaurant: true, gym: true, bar: false, airportShuttle: false, businessCenter: false, parking: true },
    smartScore: 79,
    ecoScore: 91,
    ecoBadges: ["Yoga Retreat Certified", "Organic Food", "River Cleanup"],
    moodTags: ["spiritual", "adventure", "peaceful"],
    nearbyExperiences: [{ name: "Laxman Jhula", type: "Bridge", distance: "1 km", rating: 4.4 }, { name: "Beatles Ashram", type: "Historical", distance: "3 km", rating: 4.6 }],
    location: { latitude: 30.0869, longitude: 78.2676, address: { street: "Tapovan Road", city: "Rishikesh", state: "Uttarakhand", country: "India", zipCode: "249192" } },
  },
  {
    name: "The Amber Courtyard",
    city: "Delhi",
    country: "India",
    description: "A boutique heritage hotel in the heart of Old Delhi. Walk to Red Fort, Jama Masjid, and Chandni Chowk. Experience Mughal architecture blended with contemporary luxury.",
    type: ["Hotel"],
    adultCount: 2,
    childCount: 1,
    facilities: ["Free WiFi", "Restaurant", "Fitness Center", "Business Center", "Airport Shuttle"],
    pricePerNight: 5500,
    starRating: 4,
    imageUrls: allHotelImages[hotelIndex++],
    contact: { phone: "+91-11-2327-3000", email: "info@ambercourtyard.com", website: "" },
    policies: { checkInTime: "2:00 PM", checkOutTime: "12:00 PM", cancellationPolicy: "Free cancellation up to 24 hours", petPolicy: "No pets", smokingPolicy: "Non-smoking rooms" },
    amenities: { wifi: true, pool: false, spa: false, restaurant: true, gym: true, bar: false, airportShuttle: true, businessCenter: true, parking: false },
    smartScore: 84,
    ecoScore: 70,
    ecoBadges: ["Heritage Conservation"],
    moodTags: ["cultural", "city", "historical"],
    nearbyExperiences: [{ name: "Red Fort", type: "Fortress", distance: "1 km", rating: 4.5 }, { name: "Jama Masjid", type: "Mosque", distance: "0.5 km", rating: 4.6 }],
    location: { latitude: 28.6448, longitude: 77.241, address: { street: "Chandni Chowk", city: "Delhi", state: "Delhi", country: "India", zipCode: "110006" } },
  },
  {
    name: "Tea Garden Bungalow",
    city: "Ooty",
    country: "India",
    description: "A charming colonial-style bungalow surrounded by tea plantations in the Nilgiri Hills. Enjoy cool mountain air, homemade chocolates, and scenic nature walks.",
    type: ["Cottage", "B&B"],
    adultCount: 3,
    childCount: 2,
    facilities: ["Free WiFi", "Free Parking", "Restaurant"],
    pricePerNight: 3500,
    starRating: 3,
    imageUrls: allHotelImages[hotelIndex++],
    contact: { phone: "+91-423-244-2001", email: "stay@teagardenbungalow.in", website: "" },
    policies: { checkInTime: "12:00 PM", checkOutTime: "11:00 AM", cancellationPolicy: "Free cancellation up to 48 hours", petPolicy: "Pets welcome", smokingPolicy: "Designated areas" },
    amenities: { wifi: true, pool: false, spa: false, restaurant: true, gym: false, bar: false, airportShuttle: false, businessCenter: false, parking: true },
    smartScore: 77,
    ecoScore: 89,
    ecoBadges: ["Organic Tea Garden", "Rainwater Harvesting", "Zero Plastic"],
    moodTags: ["peaceful", "nature", "family"],
    nearbyExperiences: [{ name: "Botanical Garden", type: "Garden", distance: "3 km", rating: 4.5 }, { name: "Doddabetta Peak", type: "Mountain", distance: "10 km", rating: 4.4 }],
    location: { latitude: 11.4102, longitude: 76.695, address: { street: "Tea Garden Road", city: "Ooty", state: "Tamil Nadu", country: "India", zipCode: "643001" } },
  },
  {
    name: "The Coral Reef Resort",
    city: "Andaman",
    country: "India",
    description: "Beachfront paradise on Havelock Island. Crystal-clear waters, vibrant coral reefs, and tropical forests make this the ultimate destination for snorkeling and relaxation.",
    type: ["Resort"],
    adultCount: 2,
    childCount: 2,
    facilities: ["Free WiFi", "Swimming Pool", "Restaurant", "Free Parking", "Bar/Lounge"],
    pricePerNight: 8200,
    starRating: 4,
    imageUrls: allHotelImages[hotelIndex++],
    contact: { phone: "+91-3192-282-001", email: "info@coralreefandaman.com", website: "" },
    policies: { checkInTime: "2:00 PM", checkOutTime: "11:00 AM", cancellationPolicy: "50% refund within 7 days", petPolicy: "No pets", smokingPolicy: "Designated areas" },
    amenities: { wifi: true, pool: true, spa: false, restaurant: true, gym: false, bar: true, airportShuttle: false, businessCenter: false, parking: true },
    isFeatured: true,
    smartScore: 90,
    ecoScore: 94,
    ecoBadges: ["Coral Reef Protection", "Eco-Friendly Materials", "Solar Powered"],
    moodTags: ["beach", "adventure", "relaxation"],
    nearbyExperiences: [{ name: "Radhanagar Beach", type: "Beach", distance: "1 km", rating: 4.9 }, { name: "Elephant Beach", type: "Beach", distance: "5 km", rating: 4.7 }],
    location: { latitude: 11.9751, longitude: 92.9756, address: { street: "Beach Road No. 5", city: "Havelock Island", state: "Andaman and Nicobar Islands", country: "India", zipCode: "744211" } },
  },
  {
    name: "The Stepwell Heritage Hotel",
    city: "Jodhpur",
    country: "India",
    description: "A restored haveli near the iconic Mehrangarh Fort. Enjoy authentic Marwari cuisine, traditional music evenings, and stunning blue city views from the rooftop.",
    type: ["Hotel", "B&B"],
    adultCount: 3,
    childCount: 1,
    facilities: ["Free WiFi", "Restaurant", "Spa", "Free Parking", "Airport Shuttle"],
    pricePerNight: 4800,
    starRating: 4,
    imageUrls: allHotelImages[hotelIndex++],
    contact: { phone: "+91-291-263-4001", email: "stay@stepwelljodhpur.in", website: "" },
    policies: { checkInTime: "1:00 PM", checkOutTime: "11:00 AM", cancellationPolicy: "Free cancellation up to 48 hours", petPolicy: "No pets", smokingPolicy: "Non-smoking" },
    amenities: { wifi: true, pool: false, spa: true, restaurant: true, gym: false, bar: false, airportShuttle: true, businessCenter: false, parking: true },
    smartScore: 81,
    ecoScore: 76,
    ecoBadges: ["Heritage Conservation", "Local Artisan Support"],
    moodTags: ["heritage", "cultural", "romantic"],
    nearbyExperiences: [{ name: "Mehrangarh Fort", type: "Fortress", distance: "1.5 km", rating: 4.8 }, { name: "Jaswant Thada", type: "Memorial", distance: "2 km", rating: 4.5 }],
    location: { latitude: 26.2389, longitude: 73.0243, address: { street: "Sardarpura", city: "Jodhpur", state: "Rajasthan", country: "India", zipCode: "342003" } },
  },
  {
    name: "The Spice Route Hotel",
    city: "Coorg",
    country: "India",
    description: "Nestled in coffee plantations and spice gardens, this plantation stay offers estate walks, organic farm-to-table dining, and misty mountain views in the Scotland of India.",
    type: ["Resort", "Cottage"],
    adultCount: 4,
    childCount: 2,
    facilities: ["Free WiFi", "Swimming Pool", "Restaurant", "Free Parking", "Spa"],
    pricePerNight: 5500,
    starRating: 4,
    imageUrls: allHotelImages[hotelIndex++],
    contact: { phone: "+91-8272-220-001", email: "info@spiceroutecoorg.in", website: "" },
    policies: { checkInTime: "1:00 PM", checkOutTime: "11:00 AM", cancellationPolicy: "Free cancellation up to 48 hours", petPolicy: "Pets welcome", smokingPolicy: "Designated areas" },
    amenities: { wifi: true, pool: true, spa: true, restaurant: true, gym: false, bar: false, airportShuttle: false, businessCenter: false, parking: true },
    smartScore: 85,
    ecoScore: 93,
    ecoBadges: ["Organic Farming", "Wildlife Conservation", "Solar Powered"],
    moodTags: ["nature", "peaceful", "food"],
    nearbyExperiences: [{ name: "Abbey Falls", type: "Waterfall", distance: "5 km", rating: 4.4 }, { name: "Dubare Elephant Camp", type: "Wildlife", distance: "12 km", rating: 4.6 }],
    location: { latitude: 12.3375, longitude: 75.8069, address: { street: "Madikeri Road", city: "Coorg", state: "Karnataka", country: "India", zipCode: "571201" } },
  },
  {
    name: "The Gateway Suites",
    city: "Hyderabad",
    country: "India",
    description: "A contemporary luxury hotel near the historic Charminar. Modern amenities, rooftop infinity pool, and the best biryani in the city — all under one roof.",
    type: ["Hotel"],
    adultCount: 2,
    childCount: 2,
    facilities: ["Free WiFi", "Swimming Pool", "Restaurant", "Fitness Center", "Business Center", "Spa", "Airport Shuttle", "Free Parking"],
    pricePerNight: 6000,
    starRating: 5,
    imageUrls: allHotelImages[hotelIndex++],
    contact: { phone: "+91-40-6631-0000", email: "reservations@gatewaysuiteshyd.com", website: "" },
    policies: { checkInTime: "2:00 PM", checkOutTime: "12:00 PM", cancellationPolicy: "Free cancellation up to 24 hours", petPolicy: "No pets", smokingPolicy: "Non-smoking property" },
    amenities: { wifi: true, pool: true, spa: true, restaurant: true, gym: true, bar: true, airportShuttle: true, businessCenter: true, parking: true },
    smartScore: 89,
    ecoScore: 74,
    ecoBadges: ["Energy Efficient", "Water Recycling"],
    moodTags: ["luxury", "city", "food"],
    nearbyExperiences: [{ name: "Charminar", type: "Monument", distance: "2 km", rating: 4.5 }, { name: "Golconda Fort", type: "Fortress", distance: "8 km", rating: 4.6 }],
    location: { latitude: 17.385, longitude: 78.4867, address: { street: "Abids Road", city: "Hyderabad", state: "Telangana", country: "India", zipCode: "500001" } },
  },
  {
    name: "The Lakeview Lodge",
    city: "Nainital",
    country: "India",
    description: "A cozy lakeside lodge with panoramic views of Naini Lake. Perfect for couples and families seeking tranquility, boating adventures, and crisp mountain air.",
    type: ["Hotel", "B&B"],
    adultCount: 3,
    childCount: 2,
    facilities: ["Free WiFi", "Restaurant", "Free Parking"],
    pricePerNight: 3000,
    starRating: 3,
    imageUrls: allHotelImages[hotelIndex++],
    contact: { phone: "+91-5942-235-001", email: "info@lakeviewlodge.in", website: "" },
    policies: { checkInTime: "12:00 PM", checkOutTime: "11:00 AM", cancellationPolicy: "Free cancellation up to 24 hours", petPolicy: "No pets", smokingPolicy: "Non-smoking rooms" },
    amenities: { wifi: true, pool: false, spa: false, restaurant: true, gym: false, bar: false, airportShuttle: false, businessCenter: false, parking: true },
    smartScore: 75,
    ecoScore: 83,
    ecoBadges: ["Lake Conservation", "Local Sourcing"],
    moodTags: ["peaceful", "nature", "family"],
    nearbyExperiences: [{ name: "Naini Lake", type: "Lake", distance: "0 km", rating: 4.5 }, { name: "Snow View Point", type: "Viewpoint", distance: "3 km", rating: 4.3 }],
    location: { latitude: 29.3919, longitude: 79.4542, address: { street: "Mallital", city: "Nainital", state: "Uttarakhand", country: "India", zipCode: "263001" } },
  },
];

async function seedHotels() {
  if (!process.env.MONGODB_CONNECTION_STRING) {
    console.error("MONGODB_CONNECTION_STRING not set in .env");
    process.exit(1);
  }

  try {
    await mongoose.connect(process.env.MONGODB_CONNECTION_STRING);
    console.log("Connected to MongoDB");

    const ownerUser = await User.findOne({ role: "hotel_owner" });
    if (!ownerUser) {
      console.error("No hotel_owner user found. Run seed-accounts.ts first.");
      process.exit(1);
    }

    await Hotel.deleteMany({});
    console.log("Cleared existing hotels");

    const hotelsWithUser = hotels.map((h) => ({
      ...h,
      userId: ownerUser._id.toString(),
      lastUpdated: new Date(),
      totalBookings: Math.floor(Math.random() * 200) + 10,
      totalRevenue: Math.floor(Math.random() * 500000) + 50000,
      averageRating: parseFloat((3.5 + Math.random() * 1.5).toFixed(1)),
      reviewCount: Math.floor(Math.random() * 150) + 5,
      isActive: true,
      nearbyExperiences: h.nearbyExperiences?.map((e) => ({
        name: e.name,
        type: e.type,
        distance: e.distance,
        rating: e.rating,
      })),
    }));

    await Hotel.collection.insertMany(
      hotelsWithUser.map((h) => ({
        ...h,
        verificationStatus: "approved",
        createdAt: new Date(),
        updatedAt: new Date(),
        __v: 0,
        imageUrls: h.imageUrls,
        facilities: h.facilities,
        type: h.type,
        ecoBadges: h.ecoBadges,
        contact: h.contact,
        policies: h.policies,
        amenities: h.amenities,
        location: h.location,
        moodTags: h.moodTags,
        nearbyExperiences: h.nearbyExperiences,
      }))
    );
    console.log(`Inserted ${hotelsWithUser.length} hotels`);

    console.log("\nSeed complete!");
    process.exit(0);
  } catch (error) {
    console.error("Seed failed:", error);
    process.exit(1);
  }
}

seedHotels();
